Add permissons for the fargate role to assume describe instance role
nationalarchives/tdr-terraform-modules pull request #121
Opened 2021-06-18 15:38 UTC by MancunianSam

There is a role in the sub accounts that is used to describe ec2
instances so we can determine if the bastion needs to be deleted. This
allows Jenkins to pass the role.

2021-06-24 09:06 UTC, suzannehamilton approved these changes

2021-06-24 09:06 UTC, suzannehamilton requested changes
Sorry, I approved this then realised there's no permissions for prod. Is there a specific reason for that?

2021-06-24 09:26 UTC, MancunianSam commented
I was going off the assumption that we weren't having prod bastions but we are. I've added the role in.

2021-06-25 08:30 UTC, suzannehamilton approved these changes

2021-06-25 08:55 UTC, merged